<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Robson Bolsas e Variedades</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f9f9f9;
      margin: 0;
      padding: 20px;
    }

    header {
      text-align: center;
      background-color: #333;
      color: white;
      padding: 20px 10px;
    }

    h1 {
      margin: 0;
    }

    .product {
      background: white;
      padding: 15px;
      margin: 10px auto;
      border-radius: 10px;
      box-shadow: 0 2px 5px rgba(0,0,0,0.1);
      max-width: 500px;
      display: flex;
      justify-content: space-between;
      font-size: 18px;
    }

    .whatsapp {
      display: block;
      text-align: center;
      background-color: #25D366;
      color: white;
      padding: 15px;
      margin: 30px auto;
      max-width: 300px;
      border-radius: 50px;
      text-decoration: none;
      font-size: 18px;
      font-weight: bold;
    }

    .whatsapp:hover {
      background-color: #20b954;
    }
  </style>
</head>
<body>

  <header>
    <h1>Robson Bolsas e Variedades</h1>
    <p>Os melhores produtos pelo menor preço!</p>
  </header>

  <!-- Lista de Produtos -->
  <div class="product">Relógio <span>R$ 20,00</span></div>
  <div class="product">Toca <span>R$ 20,00</span></div>
  <div class="product">Meias (3 por) <span>R$ 8,00</span></div>
  <div class="product">Bolsas de lona <span>R$ 55,00</span></div>
  <div class="product">Guarda chuva <span>R$ 14,99</span></div>
  <div class="product">Chinelo <span>R$ 9,99</span></div>
  <div class="product">Balança <span>R$ 20,00</span></div>
  <div class="product">Pulseira de relógio <span>R$ 10,00</span></div>
  <div class="product">Toca CD <span>R$ 90,00</span></div>
  <div class="product">TV Box <span>R$ 130,00</span></div>
  <div class="product">Óculos <span>R$ 20,00</span></div>
  <div class="product">Rádio <span>R$ 28,00</span></div>
  <div class="product">Lanterna <span>R$ 15,00</span></div>
  <div class="product">Cartão de memória <span>R$ 26,00</span></div>
  <div class="product">Pochete <span>R$ 20,00</span></div>
  <div class="product">Rádio moderno <span>R$ 70,00</span></div>
  <div class="product">Mochila <span>R$ 50,00</span></div>
  <div class="product">Bomba de encher pneu <span>R$ 30,00</span></div>
  <div class="product">Bolas <span>R$ 20,00</span></div>
  <div class="product">Cinto <span>R$ 15,00</span></div>
  <div class="product">Bolsa grande <span>R$ 50,00</span></div>
  <div class="product">Balança de cozinha <span>R$ 35,00</span></div>
  <div class="product">Caixinha JBL <span>R$ 45,00</span></div>
  <div class="product">Dominó <span>R$ 20,00</span></div>
  <div class="product">Carregador de pilhas <span>R$ 55,00</span></div>
  <div class="product">Suporte de celular <span>R$ 20,00</span></div>
  <div class="product">Transformador <span>R$ 20,00</span></div>
  <div class="product">Calculadora grande <span>R$ 18,00</span></div>
  <div class="product">Câmera lâmpada <span>R$ 70,00</span></div>
  <div class="product">Câmera <span>R$ 120,00</span></div>
  <div class="product">Carregador <span>R$ 15,00</span></div>
  <div class="product">Guarda chuva grande <span>R$ 18,00</span></div>
  <div class="product">Caixa de som grande <span>R$ 140,00</span></div>
  <div class="product">Boné <span>R$ 15,00</span></div>
  <div class="product">Pilhas <span>R$ 8,00 cada</span></div>
  <div class="product">Maquininha Dragão <span>R$ 18,00</span></div>
  <div class="product">Caixa de ferramenta <span>R$ 25,00</span></div>
  <div class="product">Power Bank 10000mAh <span>R$ 25,00</span></div>

  <!-- Botão WhatsApp -->
  <a class="whatsapp" href="https://wa.me/5574999693418" target="_blank">
    Fazer pedido no WhatsApp
  </a>

</body>
</html>
